# Generated by Django 3.2.13 on 2022-06-13 16:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchBarIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField()),
                ("type", models.TextField()),
                ("affiliations", models.TextField()),
                ("project_ids", models.TextField()),
                ("word_bag", models.TextField()),
                (
                    "word_bag_search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "affiliations_search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "project_ids_search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="searchbarindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=[
                    "project_ids_search_vector",
                    "affiliations_search_vector",
                    "word_bag_search_vector",
                ],
                name="search_bar_gin_index",
            ),
        ),
    ]
